version: '3.2'

services:
  caddy:
    image: abiosoft/caddy:1.0.1
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddyNetwork
    deploy:
      placement:
        constraints:
          - node.role == manager

  esmainnet:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    environment:
      - cluster.name=mainnet-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esMainnetData:/usr/share/elasticsearch/data
    networks:
      - esMainnetNetwork

  flomainnet:
    image: daviortega/go-flod:0.15.2
    ports:
      - 7313:7313
    volumes:
      - flod:/data
    env_file:
      - flod.env
    networks:
      - floNet
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  ipfs:
    image: ipfs/go-ipfs:master
    environment:
      - IPFS_PROFILE=server
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    volumes:
      - ./ipfsStaging:/export
      - ipfsData:/data/ipfs
    networks:
      - caddyNetwork
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  floNet:
  caddyNetwork:
  esMainnetNetwork:

volumes:
  flod:
  ipfsData:
  caddy:
  esMainnetData:
